$ErrorActionPreference='Stop'
$Repo=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$PriorGoCache=$env:GOCACHE;$PriorGoTmp=$env:GOTMPDIR;$GoCache=Join-Path $env:TEMP ("wingless-up54c-gocache-"+$PID);$GoTmp=Join-Path $env:TEMP ("wingless-up54c-gotmp-"+$PID)
New-Item -ItemType Directory -Force -Path $GoCache|Out-Null;New-Item -ItemType Directory -Force -Path $GoTmp|Out-Null;$env:GOCACHE=$GoCache;$env:GOTMPDIR=$GoTmp
Push-Location $Repo
try{
 Write-Host '=== WINGLESS UP-54C FOUR BANK NOISE LADDER ==='
 go env -w GOFLAGS=-buildvcs=false;if($LASTEXITCODE-ne 0){throw 'UP54C_GO_ENV_FAILED'};go clean -cache -testcache;if($LASTEXITCODE-ne 0){throw 'UP54C_GO_CLEAN_FAILED'};go run ./cmd/ice build;if($LASTEXITCODE-ne 0){throw 'UP54C_ICE_BUILD_FAILED'};go run ./cmd/ice validate;if($LASTEXITCODE-ne 0){throw 'UP54C_ICE_VALIDATE_FAILED'}
 go test ./unitary ./cmd/unitary-up54c-four-bank-noise -count=1;if($LASTEXITCODE-ne 0){throw 'UP54C_FOCUSED_TEST_FAILED'};go test ./... -count=1;if($LASTEXITCODE-ne 0){throw 'UP54C_FULL_REGRESSION_FAILED'}
 $P1=((go run ./cmd/unitary-up54c-four-bank-noise)|Out-String).Trim();if($LASTEXITCODE-ne 0){throw 'UP54C_PROBE1_FAILED'};$P2=((go run ./cmd/unitary-up54c-four-bank-noise)|Out-String).Trim();if($LASTEXITCODE-ne 0){throw 'UP54C_PROBE2_FAILED'};if($P1-cne $P2){throw 'UP54C_NONDETERMINISTIC_OUTPUT'}
 $R=$P1|ConvertFrom-Json;if($R.schema-cne 'wingless.up54c-four-bank-noise-ladder.v1'){throw 'UP54C_SCHEMA_MISMATCH'};if(-not $R.phase_tags_frozen){throw 'UP54C_TAGS_CHANGED'};if([int]$R.points.Count-ne 14){throw 'UP54C_POINT_COUNT'}
 Write-Host $P1;Write-Host '';Write-Host '=== SCIENTIFIC DIAGNOSIS (does not control harness acceptance) ===';foreach($B in $R.boundaries){Write-Host "banks=$($B.banks) max_pass=$($B.maximum_passing_noise) first_fail=$($B.first_failing_noise)"};foreach($P in $R.points){Write-Host "banks=$($P.banks) noise=$($P.memory_noise) gate=$($P.gate) value=$($P.coherence_value_accuracy) exact=$($P.coherence_exact_scenario_accuracy) margin=$($P.coherence_minimum_margin) magnitude=$($P.magnitude_value_accuracy)"};Write-Host 'WINGLESS_UP54_HARNESS_PASS'
}finally{Pop-Location;if($null-eq $PriorGoCache){Remove-Item Env:GOCACHE -ErrorAction SilentlyContinue}else{$env:GOCACHE=$PriorGoCache};if($null-eq $PriorGoTmp){Remove-Item Env:GOTMPDIR -ErrorAction SilentlyContinue}else{$env:GOTMPDIR=$PriorGoTmp};Remove-Item -Recurse -Force $GoCache -ErrorAction SilentlyContinue;Remove-Item -Recurse -Force $GoTmp -ErrorAction SilentlyContinue}
