package unitary
import("fmt";"sort")
const UP255CHistoryPuritySchema="wingless.up255c-history-augmented-purity.v1"
type UP255CPartition struct{Name string `json:"name"`;Groups int `json:"groups"`;PureGroups int `json:"pure_groups"`;MixedGroups int `json:"mixed_groups"`;MaxClassesPerGroup int `json:"max_classes_per_group"`}
type UP255CResult struct{Schema string `json:"schema"`;Experiment string `json:"experiment"`;SourceUP254CSeal string `json:"source_up254c_seal"`;PairedInitialStates int `json:"paired_initial_states"`;ParentClassification string `json:"parent_classification"`;ParentMixedGroups int `json:"parent_mixed_groups"`;DiagnosticOnly bool `json:"diagnostic_only"`;InterventionChanged bool `json:"intervention_changed"`;ClassifierTrainingUsed bool `json:"classifier_training_used"`;AdaptiveFeatureSelectionUsed bool `json:"adaptive_feature_selection_used"`;LiveActivation bool `json:"live_activation"`;Partitions []UP255CPartition `json:"partitions"`;Classification string `json:"classification"`}
func up255cStatic(s UP223CSnapshot)string{return fmt.Sprintf("ea=%d|pe=%t|hd=%d|a0=%d|a1=%d|a2=%d|a3=%d|adv=%d|noq=%d",s.EndangeredAge,s.PredictedIsEndangered,s.HandDistance,s.Age0,s.Age1,s.Age2,s.Age3,s.AdversarialHorizon,s.NoQueryHorizon)}
func up255cPart(name string,keys []string,classes []string)UP255CPartition{g:=map[string]map[string]bool{};for i,k:=range keys{if g[k]==nil{g[k]=map[string]bool{}};g[k][classes[i]]=true};ks:=make([]string,0,len(g));for k:=range g{ks=append(ks,k)};sort.Strings(ks);r:=UP255CPartition{Name:name,Groups:len(g)};for _,k:=range ks{n:=len(g[k]);if n==1{r.PureGroups++}else{r.MixedGroups++};if n>r.MaxClassesPerGroup{r.MaxClassesPerGroup=n}};return r}
func RunUP255C()(UP255CResult,error){
 p,err:=RunUP254C();if err!=nil{return UP255CResult{},err}
 cohorts:=[][]int{{0,9,10,15},{1,4,11,14},{2,5,8,13},{3,6,7,12}};hands:=[]int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15}
 static,current,traj,classes:=[]string{},[]string{},[]string{},[]string{}
 r:=UP255CResult{Schema:UP255CHistoryPuritySchema,Experiment:"UP-255C-history-augmented-purity",SourceUP254CSeal:"7282febd8309d13ca9a601d876415cb9761d539d",ParentClassification:p.Classification,ParentMixedGroups:p.MixedGroups,DiagnosticOnly:true}
 for _,co:=range cohorts{for _,hand:=range hands{x,e,ok:=up161cTriggerState(hand,co);if !ok{continue};s:=up223cSnapshot(x,e,0);a,er:=up237cRun(x,e,22,"alternating_shield","fixed_offset_refresh");if er!=nil{return UP255CResult{},er};b,er:=up237cRun(x,e,0,"fixed_offset_refresh","alternating_shield");if er!=nil{return UP255CResult{},er};cl:=up246cClass(a,b);sk:=up255cStatic(s);ck:=fmt.Sprintf("%s|ae=%t|ac=%s|be=%t|bc=%s",sk,a.EventPresent,a.CurrentSignature,b.EventPresent,b.CurrentSignature);tk:=fmt.Sprintf("%s|at=%s|bt=%s",ck,a.TrajectorySignature,b.TrajectorySignature);static=append(static,sk);current=append(current,ck);traj=append(traj,tk);classes=append(classes,cl);r.PairedInitialStates++}}
 ps:=up255cPart("STATIC9",static,classes);pc:=up255cPart("STATIC9_CURRENT",current,classes);pt:=up255cPart("STATIC9_TRAJECTORY",traj,classes);r.Partitions=[]UP255CPartition{ps,pc,pt}
 if p.Classification!="FULL_NATIVE_STATE_NONSEPARABLE"||ps.MixedGroups!=p.MixedGroups{r.Classification="ANCHOR_NOT_REPRODUCED"}else if pc.MixedGroups==0{r.Classification="CURRENT_STATE_RESOLVES_ALIASING"}else if pt.MixedGroups==0{r.Classification="TRAJECTORY_RESOLVES_ALIASING"}else if pc.MixedGroups<ps.MixedGroups||pt.MixedGroups<ps.MixedGroups{r.Classification="HISTORY_REDUCES_NOT_RESOLVES"}else{r.Classification="HISTORY_DOES_NOT_REDUCE_ALIASING"}
 return r,nil
}
